version: '3.8'

services:
  starwars-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: