spring:
  application:
    name: starwars_api
  messages:
    basename: message

  datasource:
    url: jdbc:mysql://localhost:3306/starwars_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    url: jdbc:mysql://localhost:3306/starwars_db
    default-schema: starwars_db
    user: root
    password: root